name: Publish

on:
  push:
    branches: [ "release/v*" ]

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for nbgv
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
          include-prerelease: false
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish "src/AOGuildHelper/AOGuildHelper.csproj" --configuration Release -p:ContinuousIntegrationBuild=true --self-contained false -p:PublishSingleFile=true --output publish
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.nbgv.outputs.SemVer2 }}
          files: "publish/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}